const cars = [
  {
    id: '67rdca3eeb7f6fgeed471815',
    name: 'Toyota Yaris 3 Doors',
    model: 'Yaris',
    brand: 'Toyota',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2019,
    image: '',
    color: '#e74c3c',
    body: 'Hatchback',
    doors: 3,
    price: 10500,
    stock: 3,
    rating: 3.3,
  },
  {
    id: '67rdca3eeb7f6fgeed471816',
    name: 'Toyota Camry 4 Doors',
    model: 'Camry',
    brand: 'Toyota',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2018,
    image: '',
    color: '#3498db',
    body: 'Sedan',
    doors: 4,
    price: 17000,
    stock: 7,
    rating: 4.5,
  },
  {
    id: '67rdca3eeb7f6fgeed471817',
    name: 'Toyota Yaris 5 Doors',
    model: 'Yaris',
    brand: 'Toyota',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2020,
    image: '',
    color: '#2ecc71',
    body: 'Hatchback',
    doors: 5,
    price: 11300,
    stock: 10,
    rating: 19,
  },
  {
    id: '67rdca3eeb7f6fgeed471818',
    name: 'Toyota Avalon 5 Doors',
    model: 'Avalon',
    brand: 'Toyota',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2017,
    image: '',
    color: '#9b59b6',
    body: 'Sedan',
    doors: 5,
    price: 14300,
    stock: 29,
    rating: 4.1,
  },
  {
    id: '67rdca3eeb7f6fgeed471819',
    name: 'Toyota Tacoma 4 Doors',
    model: 'Tacoma',
    brand: 'Toyota',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2021,
    image: '',
    color: '#e74c3c',
    body: 'Truck',
    doors: 4,
    price: 18450,
    stock: 7,
    rating: 4.7,
  },
  {
    id: '67rdca3eeb7f6fgeed471820',
    name: 'Toyota RAV4 5 Doors',
    model: 'RAV4',
    brand: 'Toyota',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2022,
    image: '',
    color: '#3498db',
    body: 'SUV',
    doors: 5,
    price: 21100,
    stock: 10,
    rating: 4.9,
  },
  {
    id: '67rdca3eeb7f6fgeed471821',
    name: 'Toyota Hilux Single Cab 2 Doors',
    model: 'Hilux Single Cab',
    brand: 'Toyota',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2003,
    image: '',
    color: '#2ecc71',
    body: 'Truck',
    doors: 2,
    price: 19180,
    stock: 2,
    rating: 3.1,
  },
  {
    id: '67rdca3eeb7f6fgeed471822',
    name: 'Honda City 5 Doors',
    model: 'City',
    brand: 'Honda',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2009,
    image: '',
    color: '#9b59b6',
    body: 'Hatchback',
    doors: 5,
    price: 13100,
    stock: 5,
    rating: 4.0,
  },
  {
    id: '67rdca3eeb7f6fgeed471823',
    name: 'Honda Amaze 4 Doors',
    model: 'Amaze',
    brand: 'Honda',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2005,
    image: '',
    color: '#e74c3c',
    body: 'Sedan',
    doors: 4,
    price: 10300,
    stock: 9,
    rating: 3.2,
  },
  {
    id: '67rdca3eeb7f6fgeed471824',
    name: 'Honda Passport 5 Doors',
    model: 'Passport',
    brand: 'Honda',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2011,
    image: '',
    color: '#3498db',
    body: 'Crossover',
    doors: 5,
    price: 38370,
    stock: 8,
    rating: 4.7,
  },
  {
    id: '67rdca3eeb7f6fgeed471825',
    name: 'Honda Odyssey 5 Doors',
    model: 'Odyssey',
    brand: 'Honda',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2014,
    image: '',
    color: '#2ecc71',
    body: 'Minivan',
    doors: 5,
    price: 12000,
    stock: 15,
    rating: 3.7,
  },
  {
    id: '67rdca3eeb7f6fgeed471826',
    name: 'Honda Civic 4 Doors',
    model: 'Civic',
    brand: 'Honda',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2016,
    image: '',
    color: '#9b59b6',
    body: 'Sedan',
    doors: 4,
    price: 12370,
    stock: 25,
    rating: 5,
  },
  {
    id: '67rdca3eeb7f6fgeed471827',
    name: 'Ford Escape 5 Doors',
    model: 'Escape',
    brand: 'Ford',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2009,
    image: '',
    color: '#16a085',
    body: 'SUV',
    doors: 5,
    price: 23750,
    stock: 17,
    rating: 4.2,
  },
  {
    id: '67rdca3eeb7f6fgeed471828',
    name: 'Ford Ranger 2 Doors',
    model: 'Ranger',
    brand: 'Ford',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2001,
    image: '',
    color: '#f1c40f',
    body: 'Truck',
    doors: 2,
    price: 15700,
    stock: 1,
    rating: 3.7,
  },
  {
    id: '67rdca3eeb7f6fgeed471829',
    name: 'Ford Transit 2 Doors',
    model: 'Transit',
    brand: 'Ford',
    description:
      // eslint-disable-next-line max-len
      'Compared to the regular Yaris, body has been modified substantially to improve the car\'s looks and performance at the same time. The GR has a roofline that has been lowered by 91 mm and the two doors feature a frameless design for a true coupe look. The body shell is made exclusively from lightweight materials like carbon fiber polymers and aluminum, while the platform allows a rear track with increased width and a double wishbone suspension. The three-cylinder, turbocharged 1.6-liter engine has been pushed further back into the body for better weight distribution while the battery has been relocated to the trunk. The 261 horsepower and 360 Nm of torque go to all four wheels thanks to an advanced all-wheel-drive system that can send up to 100 percent of torque to either the front or the rear, depending on driving situation.',
    release: 2007,
    image: '',
    color: '#2c3e50',
    body: 'Passenger VAN',
    doors: 2,
    price: 31200,
    stock: 4,
    rating: 4.1,
  },
];

export default cars;
